<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="{{ config.sw_group_url }}" target="_blank">{{ config.author }}</a><br>
      Documentation licensed under <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.
      Attribution should be creditted to Tommy Chen, for his original work in the <a href="https://hexo.io/">Hexo Site Docs Theme</a>, which has been used as the theme of this documentation site.
    </div>
  </div>
</footer>
